version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout
      - run:
          name: Update npm version
          command: npm install -g npm@10.8.2
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ checksum "package-lock.json" }}

  deploy:
    docker:
      - image: cimg/node:18.20.7
    steps:
      - run:
          name: Deploy application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ProjectApplication/; git clone https://github.com/LDNP/ProjectApplication.git; source ProjectApplication/deploy.sh"
