version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_frontend
      - test_all:
          requires:
            - build_frontend

jobs:
  build_frontend:
    working_directory: ~/ProjectApplication
    docker:
      - image: cimg/node:18.20.7
    steps:
      - checkout

      - run:
          name: Update npm version
          command: npm install -g npm@10.8.2  

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build React app
          command: npm run build

      - save_cache:
          paths:
            - ~/.npm
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}

  test_all:
    docker:
      - image: cimg/node:18.20.7
    working_directory: ~/ProjectApplication
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Run both frontend and backend tests
          command: npm run test:all  # Runs the "test:all" script to run both frontend and backend tests concurrently